Rendezvous-v0:
  env_wrapper:
    - swarm_zoo.point_envs.rendezvous.SetObsWrapper
    - supersuit.pettingzoo_env_to_vec_env_v1
    - supersuit.concat_vec_envs_v1:
        num_vec_envs: 4
        num_cpus: 0
        base_class: 'gymnasium'
  normalize: true
  n_envs: 1
  policy: src.swarm_rl.policy_modules.MeanEmbeddingPolicy
  n_timesteps: !!float 1e6
  batch_size: 64
  n_steps: 512
  gamma: 0.98
  learning_rate: 2.0633e-05
  ent_coef: 0.000401762
  clip_range: 0.1
  n_epochs: 20
  gae_lambda: 0.92
  max_grad_norm: 0.8
  vf_coef: 0.58096
  policy_kwargs: "dict(
                    log_std_init=-2,
                    ortho_init=False,
                    activation_fn=nn.ReLU,
                    net_arch=dict(pi=[64], vf=[64])
                  )"